/**
 * Glcd project
 * 
 * interrupt.h
 * 
 * Contains a simple interrupt handler for general purposes.
 * 
 * @author  Dalmir da Silva <dalmirdasilva@gmail.com>
 */

#ifndef __PIC_LEDCUBE_INTERRUPT_H
#define __PIC_LEDCUBE_INTERRUPT_H 1 

#define INTERRUPT_PRESCALER 0xff

#include <signal.h>

DEF_INTHIGH(high_interrupt_vector)
    DEF_HANDLER(SIG_TMR0, timer_0_handler)
END_DEF

uint8_t interrupt_prescaler = 0;

/*
 * This function is called by an interrupt generated by timer 0.
 */
SIGHANDLER(timer_0_handler) {
    
    if(INTCONbits.T0IF) {
  
        // Clear interrupt flag
        INTCONbits.T0IF = 0;
        
        // Disable ie
        INTCONbits.GIE = 0;
        
        // Prescaler
        if(interrupt_prescaler++ == INTERRUPT_PRESCALER) {
            interrupt_prescaler = 0;




            //glcd_buffered_handle_interrupt();
        }
        
        // Enable after
        INTCONbits.GIE = 1;
    }
}

#endif // __PIC_LEDCUBE_INTERRUPT_H

